### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by rcannood** [laminlabs/lamin-cli#90]
I'm trying to run the following:

```bash
pip install lamin_cli
lamin connect laminlabs/cellxgene
```

However, I'm currently getting the following error message:

    ! schema module 'bionty' is not installed → no access to its labels & registries (resolve via `pip install bionty`)
    Traceback (most recent call last):
      File "/home/runner/.local/bin/lamin", line 8, in <module>
        sys.exit(main())
      File "/home/runner/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in __call__
        return super().__call__(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
        return self.main(*args, **kwargs)
      File "/home/runner/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
        return __callback(*args, **kwargs)
      File "/home/runner/.local/lib/python3.10/site-packages/lamin_cli/__main__.py", line 162, in connect
        return connect_(slug=instance)
      File "/home/runner/.local/lib/python3.10/site-packages/lamindb_setup/core/cloud_sqlite_locker.py", line 230, in wrapper
        raise exc
      File "/home/runner/.local/lib/python3.10/site-packages/lamindb_setup/core/cloud_sqlite_locker.py", line 225, in wrapper
        return func(*args, **kwargs)
      File "/home/runner/.local/lib/python3.10/site-packages/lamindb_setup/_connect_instance.py", line 300, in connect
        raise e
      File "/home/runner/.local/lib/python3.10/site-packages/lamindb_setup/_connect_instance.py", line 260, in connect
        check, msg = isettings._load_db()
      File "/home/runner/.local/lib/python3.10/site-packages/lamindb_setup/core/_settings_instance.py", line 484, in _load_db
        setup_django(self)
      File "/home/runner/.local/lib/python3.10/site-packages/lamindb_setup/core/django.py", line 98, in setup_django
        django.setup(set_prefix=False)
      File "/home/runner/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/runner/.local/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
        app_config.import_models()
      File "/home/runner/.local/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
        self.models_module = import_module(models_module_name)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/runner/.local/lib/python3.10/site-packages/lnschema_core/models.py", line 27, in <module>
        from lnschema_core.types import (
      File "/home/runner/.local/lib/python3.10/site-packages/lnschema_core/types.py", line 6, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    Error: Process completed with exit code 1.

→ https://github.com/laminlabs/laminr/actions/runs/11290664910/job/31402995902?pr=33

**Comment by falexwolf** [comment]
Ah, yes. It's never been used standalone. Probably there are more issues.

Given `lamindb` will be needed to save artifacts, I'm now leaning to require `pip install lamindb` instead of `pip install lamin-cli` for `laminr`.

See:

- https://github.com/laminlabs/laminr/issues/16

We can work on making all of this slimmer; but right now the priority is to have a stable workable setup.

So, I'll for now not set up all infra to make `lamin-cli` truly standalone.
